# Generated by Django 2.2 on 2021-07-14 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_orderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_date', models.DateTimeField()),
                ('is_ordered', models.BooleanField(default=False)),
                ('is_refund_requested', models.BooleanField(default=False)),
                ('is_refund_granted', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='core.OrderProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
