# Generated by Django 2.2 on 2021-07-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_title',
        ),
    ]
