# Generated by Django 2.2 on 2021-07-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_address_address_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
    ]
