# Generated by Django 2.2 on 2021-07-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210716_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
