# Generated by Django 2.2 on 2021-07-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210716_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
    ]
