# Generated by Django 2.2 on 2021-08-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210817_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isTrend',
        ),
        migrations.CreateModel(
            name='TrendProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(to='core.Product')),
            ],
        ),
    ]
