# Generated by Django 2.2 on 2021-08-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210827_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertismentCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/advertisment/')),
            ],
        ),
    ]
