# Generated by Django 2.2 on 2021-08-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_advertismentcarousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertismentcarousel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
