# Generated by Django 2.2 on 2021-08-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210829_2136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvertismentCarousel',
            new_name='MobileCarousel',
        ),
    ]
